### ISSUE TITLE
nao  estou conseguindo mudar o destino no atalho

### ISSUE THREAD

**Issue by juuhnjin** [gabrielikiD/wuwa-pt-br#1]
boa noite gabriel, nao estou conseguindo mudar o nome na area de trabalho seguimdo esse passo ;

'"3 - Na area de trabalho va ate o atalho criado clique em propriedades e adicione "-fileopenlog" ao final de destino'"

acontece um erro. poderia me dizer se estou fazendo algo de errado?

![imagem_2024-06-07_203057588](https://github.com/gabrielikiD/wuwa-pt-br/assets/172086599/e949dd45-3b58-489e-9bf6-c7f131240def)

**Comment by gabrielikiD** [comment]
E porque esta tudo junto, na parte final onde esta escrito client-win64-shipping.exe precisa ter um espaço.

Ficando com o final nesse formato: Client-Win64-Shipping.exe" "-fileopenlog"

**Comment by juuhnjin** [comment]
bgd gabriel. fiz isso e deu certo. obgd pela resposta rapida e pelo trabalho duro.

**Comment by Enjuux** [comment]
caso atualize a tradução futuramente, vai postar por aq mesmo? ou tem algum disc pra divulgar?

**Comment by gabrielikiD** [comment]
> caso atualize a tradução futuramente, vai postar por aq mesmo? ou tem algum disc pra divulgar?

Será atualizado aqui. Em breve farei um discord também pro pessoal reportar os erros na tradução. Semana que vem irei começar a corrigir a partir de segunda, porque ai vai ter coisa acumulada.

**Comment by DiegoLima1402** [comment]
> > caso atualize a tradução futuramente, vai postar por aq mesmo? ou tem algum disc pra divulgar?
> 
> Será atualizado aqui. Em breve farei um discord também pro pessoal reportar os erros na tradução. Semana que vem irei começar a corrigir a partir de segunda, porque ai vai ter coisa acumulada.

Gostaria de ajudar na tradução. Tem alguma forma de eu te contatar diretamente?

**Comment by Enjuux** [comment]
> > > caso atualize a tradução futuramente, vai postar por aq mesmo? ou tem algum disc pra divulgar?
> > 
> > 
> > Será atualizado aqui. Em breve farei um discord também pro pessoal reportar os erros na tradução. Semana que vem irei começar a corrigir a partir de segunda, porque ai vai ter coisa acumulada.
> 
> Gostaria de ajudar na tradução. Tem alguma forma de eu te contatar diretamente?

o discord da tradução: https://discord.gg/qWHFfPXf . tenta por lá
