### ISSUE TITLE
Atualizações

### ISSUE THREAD

**Issue by lunnarpsy** [gabrielikiD/wuwa-pt-br#3]
Pelo que parece, o jogo teve uma nova atualização que o atalho não acompanha... Quando tento abrir o jogo como sempre fiz o jogo me joga uma mensagem que diz que há uma atualização disponível e que devo atualizar, porem quando vou ver na Epic (por onde baixei) não há atualizações disponíveis. Pode me ajudar?

**Comment by gabrielikiD** [comment]
Inicie o jogo pelo launcher para atualizar. depois volte a usar o atalho.
